@echo off

powershell -NoProfile -Command "Remove-Item -Recurse .\dist"
powershell -NoProfile -Command "mkdir .\dist"
powershell -NoProfile -Command "mkdir \".\dist\Psychology Imprisonment Patch\""
powershell -NoProfile -Command "Copy-Item -Recurse .\About \".\dist\Psychology Imprisonment Patch\About\""
powershell -NoProfile -Command "Copy-Item -Recurse .\1.0 \".\dist\Psychology Imprisonment Patch\""
powershell -NoProfile -Command "Get-ChildItem \".\dist\Psychology Imprisonment Patch\1.0\Source\.vs\" -Recurse -Directory | Get-ChildItem -attributes hidden | Remove-Item -Recurse -Verbose -Force"
powershell -NoProfile -Command "Remove-Item -Recurse \".\dist\Psychology Imprisonment Patch\1.0\Source\.vs\""
powershell -NoProfile -Command "Copy-Item -Recurse \".\dist\Psychology Imprisonment Patch\1.0\Source\PsychologyImprisonmentPatch\bin\Release\PsychologyImprisonmentPatch.dll\" \".\dist\Psychology Imprisonment Patch\1.0\Assemblies\PsychologyImprisonmentPatch.dll\""
powershell -NoProfile -Command "Copy-Item -Recurse \".\dist\Psychology Imprisonment Patch\1.0\Source\PsychologyImprisonmentPatch\bin\Release\0Harmony.dll\" \".\dist\Psychology Imprisonment Patch\1.0\Assemblies\0Harmony.dll\""
powershell -NoProfile -Command "Remove-Item -Recurse \".\dist\Psychology Imprisonment Patch\1.0\Assemblies\.gitnofile\""
powershell -NoProfile -Command "Remove-Item -Recurse \".\dist\Psychology Imprisonment Patch\1.0\Source\PsychologyImprisonmentPatch\bin\""
powershell -NoProfile -Command "Remove-Item -Recurse \".\dist\Psychology Imprisonment Patch\1.0\Source\PsychologyImprisonmentPatch\obj\""
powershell -NoProfile -Command "Remove-Item -Recurse \".\dist\Psychology Imprisonment Patch\1.0\Source\PsychologyImprisonmentPatch\Libraries\*.dll\""
powershell -NoProfile -Command "Copy-Item -Recurse .\1.1 \".\dist\Psychology Imprisonment Patch\""
powershell -NoProfile -Command "Get-ChildItem \".\dist\Psychology Imprisonment Patch\1.1\Source\.vs\" -Recurse -Directory | Get-ChildItem -attributes hidden | Remove-Item -Recurse -Verbose -Force"
powershell -NoProfile -Command "Remove-Item -Recurse \".\dist\Psychology Imprisonment Patch\1.1\Source\.vs\""
powershell -NoProfile -Command "Copy-Item -Recurse \".\dist\Psychology Imprisonment Patch\1.1\Source\PsychologyImprisonmentPatch\bin\Release\PsychologyImprisonmentPatch.dll\" \".\dist\Psychology Imprisonment Patch\1.1\Assemblies\PsychologyImprisonmentPatch.dll\""
powershell -NoProfile -Command "Remove-Item -Recurse \".\dist\Psychology Imprisonment Patch\1.1\Assemblies\.gitnofile\""
powershell -NoProfile -Command "Remove-Item -Recurse \".\dist\Psychology Imprisonment Patch\1.1\Source\PsychologyImprisonmentPatch\bin\""
powershell -NoProfile -Command "Remove-Item -Recurse \".\dist\Psychology Imprisonment Patch\1.1\Source\PsychologyImprisonmentPatch\obj\""
powershell -NoProfile -Command "Remove-Item -Recurse \".\dist\Psychology Imprisonment Patch\1.1\Source\PsychologyImprisonmentPatch\Libraries\*.dll\""
